DOCUMENT_IMAGES = {
    "fard": "punjab_Jamabandi.png",
    "farde": "punjab_Jamabandi.png",
    "fard jamabandi": "punjab_Jamabandi.png",
    "jamabandi": "punjab_Jamabandi.png",
    "girdawari": "punjab_Girdawari.avif",
    "khasra": "punjab_khasra_document.png",
    "khasra document": "punjab_khasra_document.png",
    "mutation": "punjab_mutation_register_intkal.png",
    "mutation register": "punjab_mutation_register_intkal.png",
    "intkal": "punjab_mutation_register_intkal.png",
    "sale deed": "sale_deed.png",
    "registry": "registry_intkal.png",
    "registry intkal": "registry_intkal.png",
    "power of attorney": "punjab_power_of_attorney.png",
    "poa": "punjab_power_of_attorney.png",
    "will": "punjab_will.png",
    "will document": "punjab_will.png",
    "partition deed": "punjab_partition_deed.png",
    "tatima": "punjab_tatima.png",
    "aks shajra": "punjab_aks_shajra.png",
    "aks shajara": "punjab_aks_shajra.png",
    "shajra": "punjab_aks_shajra.png",
    "e stamp": "e_stamp_punjab_sample.jpg",
    "estamp": "e_stamp_punjab_sample.jpg",
    "e-stamp": "e_stamp_punjab_sample.jpg",
}